# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  - pull_request
  - push

name: CI

jobs:
  coding-guidelines:
    name: Coding Guidelines
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4' ]
    steps:
      - uses: actions/checkout@v2

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}

      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}

      - name: Run friendsofphp/php-cs-fixer
        run: ./vendor/bin/php-cs-fixer fix --allow-risky=yes --dry-run --show-progress=dots --using-cache=no --verbose

  type-checker:
    name: Type Checker
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4' ]
    steps:
      - uses: actions/checkout@v2

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}

      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}

      - name: Run vimeo/psalm on internal code
        run: ./vendor/bin/psalm --config=psalm.xml --no-progress --shepherd --show-info=false --stats

  compiler-tests:
    name: Compiler tests on PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4', '8.0' ]
    steps:
      - uses: actions/checkout@v2

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}

      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}

      - name: Run unit tests to the compiler itself
        run: vendor/bin/phpunit --testsuite unit

      - name: Run integration tests to the compiler itself
        run: vendor/bin/phpunit --testsuite integration

  core-tests:
    name: Core tests on PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4', '8.0' ]
    steps:
      - uses: actions/checkout@v2

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}

      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}

      - name: Run tests to the core library
        run: composer run-script test-core

  bench-tests:
    name: Bench tests on PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4', '8.0' ]
    steps:
      - uses: actions/checkout@v2

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}

      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}

      - name: Run PHPBench
        run: vendor/bin/phpbench run --iterations=3 --warmup=1 --report=aggregate
