name: Publish docker images

on:
  push:
    tags:
      - '*'

jobs:
  repl:
    name: Docker quickstart repl
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: cd docker/repl && docker build . --file Dockerfile --tag phellang/repl:${{github.ref_name}} && docker tag phellang/repl:${{github.ref_name}} phellang/repl:latest

    - name: Docker Push
      run: docker push phellang/repl
